export default{
    arr:[
        {
            title:{
                title:"数码商城",
                tip:["笔记本","照相机"]
            },
            data:
            [
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,0,1],sellhot:true},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,1,0],sellhot:false},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,1,1],sellhot:true},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[0,1,1],sellhot:false},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,0,0],sellhot:true},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,1,0],sellhot:false}
            ]
        },
        {
            title:{
                title:"零食卖场",
                tip:["烤面筋","吸吸冰"]
            },
            data:
            [
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,0,1],sellhot:true},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,1,0],sellhot:false},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,1,1],sellhot:true},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[0,1,1],sellhot:false},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,0,0],sellhot:true},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,1,0],sellhot:false}
            ]
        },
        {
            title:{
                title:"零食卖场",
                tip:["烤面筋","吸吸冰"]
            },
            data:
            [
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,0,1],sellhot:true},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,1,0],sellhot:false},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,1,1],sellhot:true},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[0,1,1],sellhot:false},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,0,0],sellhot:true},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,1,0],sellhot:false}
            ]
        ,
        },
        {
            title:{
                title:"零食卖场",
                tip:["烤面筋","吸吸冰"]
            },
            data:
            [
                {src:"../../../../static/goods.jpg",rate:3.2,title:"苹果电脑",sell:3000,tipshow:[1,0,1],sellhot:true},
                {src:"../../../../static/goods.jpg",rate:3.3,title:"苹果电脑",sell:3000,tipshow:[1,1,0],sellhot:false},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,1,1],sellhot:true},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[0,1,1],sellhot:false},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,0,0],sellhot:true},
                {src:"../../../../static/goods.jpg",rate:4.3,title:"苹果电脑",sell:3000,tipshow:[1,1,0],sellhot:false}
            ]
        ,
        }
    ]
}
