export default {data:[
    {
        name:"童装",
        route:"food",
        sname:[
            {
                name:"阿迪王",
                route:"food?id=1"
            },
            {
                name:"阿弟王",
                route:"food?id=1"
            }
        ],
        data:[
            {
                name:"aaaaa",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },
            {
                name:"可口sdsdsd可乐",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },{
                name:"哇哈asdasd哈",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            }
        ]
    },
    {
        name:"学习",
        route:"food",
        sname:[
            {
                name:"web前端",
                route:"food?id=1"
            },
            {
                name:"java后台",
                route:"food?id=1"
            }
        ],
        data:[
            {
                name:"aaaaa",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },
            {
                name:"可口sdsdsd可乐",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },{
                name:"哇哈asdasd哈",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            }
        ]
    },
    {
        name:"乐器",
        route:"food",
        sname:[
            {
                name:"葫芦丝",
                route:"food?id=1"
            },
            {
                name:"唢呐",
                route:"food?id=1"
            }
        ],
        data:[
            {
                name:"aaaaa",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },
            {
                name:"可口sdsdsd可乐",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },{
                name:"哇哈asdasd哈",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            }
        ]
    },
    {
        name:"鞋子",
        route:"food",
        sname:[
            {
                name:"阿迪王",
                route:"food?id=1"
            },
            {
                name:"耐克",
                route:"food?id=1"
            }
        ],
        data:[
            {
                name:"aaaaa",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },
            {
                name:"可口sdsdsd可乐",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },{
                name:"哇哈asdasd哈",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            }
        ]
    },
    {
        name:"女装",
        route:"food",
        sname:[
            {
                name:"丽人时装",
                route:"food?id=1"
            },
            {
                name:"热风",
                route:"food?id=1"
            }
        ],
        data:[
            {
                name:"aaaaa",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },
            {
                name:"可口sdsdsd可乐",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },{
                name:"哇哈asdasd哈",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            }
        ]
    },
    {
        name:"珠宝",
        route:"food",
        sname:[
            {
                name:"戒指",
                route:"food?id=1"
            },
            {
                name:"项链",
                route:"food?id=1"
            }
        ],
        data:[
            {
                name:"aaaaa",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },
            {
                name:"可口sdsdsd可乐",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },{
                name:"哇哈asdasd哈",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            }
        ]
    },
    {
        name:"鞋子",
        route:"food",
        sname:[
            {
                name:"阿迪王",
                route:"food?id=1"
            },
            {
                name:"耐克",
                route:"food?id=1"
            }
        ],
        data:[
            {
                name:"aaaaa",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },
            {
                name:"可口sdsdsd可乐",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },{
                name:"哇哈asdasd哈",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            }
        ]
    },
    {
        name:"男装",
        route:"food",
        sname:[
            {
                name:"乙纯",
                route:"food?id=1"
            },
            {
                name:"斑尼鹿",
                route:"food?id=1"
            }
        ],
        data:[
            {
                name:"aaaaa",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },
            {
                name:"可口sdsdsd可乐",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },{
                name:"哇哈asdasd哈",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            }
        ]
    },
    {
        name:"休闲",
        route:"food",
        sname:[
            {
                name:"大保健",
                route:"food?id=1"
            },
            {
                name:"足疗",
                route:"food?id=1"
            }
        ],
        data:[
            {
                name:"aaaaa",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },
            {
                name:"可口sdsdsd可乐",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },{
                name:"哇哈asdasd哈",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            }
        ]
    },
    {
        name:"零食",
        route:"food",
        sname:[
            {
                name:"康师傅",
                route:"food?id=1"
            },
            {
                name:"干脆面",
                route:"food?id=1"
            }
        ],
        data:[
            {
                name:"aaaaa",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },
            {
                name:"可口sdsdsd可乐",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },{
                name:"哇哈asdasd哈",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            }
        ]
    },
    {
        name:"电子",
        route:"food",
        sname:[
            {
                name:"锁泥",
                route:"food?id=1"
            },
            {
                name:"三兴",
                route:"food?id=1"
            }
        ],
        data:[
            {
                name:"哇哈哈",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },
            {
                name:"可口可乐",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },{
                name:"哇哈哈",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            }
        ]
    },
    {
        name:"家电",
        route:"food",
        sname:[
            {
                name:"洗衣机",
                route:"food?id=1"
            },
            {
                name:"吹风筒",
                route:"food?id=1"
            }
        ],
        data:[
            {
                name:"哇哈哈",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },
            {
                name:"可口可乐",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },{
                name:"哇哈哈",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            }
        ]
    }
    ,
    {
        name:"生鲜",
        route:"food",
        sname:[
            {
                name:"青岛大虾",
                route:"food?id=1"
            },
            {
                name:"新疆切糕",
                route:"food?id=1"
            }
        ],
        data:[
            {
                name:"哇哈哈",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },
            {
                name:"可口可乐",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            },{
                name:"哇哈哈",
                route:"food?id=1",
                data:[
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"},
                    {name:"ad钙",route:"food?id=1"}
                ]
            }
        ]
    }
]
}